{
 "title": "OceanBase Metrics",
 "description": "oceanbase metrics collected from oceanbase using obagent",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "obcluster", "query": { "query": "label_values(ob_cluster_name)" } },
   {
    "name": "obzone",
    "query": {
     "query": "label_values({ob_cluster_name=~\"$obcluster\"}, obzone)"
    }
   },
   {
    "name": "observer",
    "query": {
     "query": "label_values({ob_cluster_name=~\"$obcluster\",obzone=~\"$obzone\"}, svr_ip)"
    }
   },
   {
    "name": "tenant_name",
    "query": {
     "query": "label_values({ob_cluster_name=~\"$obcluster\",obzone=~\"$obzone\",svr_ip=~\"$observer\"}, tenant_name)"
    }
   },
   {
    "name": "group",
    "query": "ob_cluster_name, obzone, svr_ip, tenant_name"
   }
  ]
 },
 "panels": [
  {
   "title": "INFINITY DEMO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ob_sysstat{stat_id=\"40002\",ob_cluster_name=~\"$obcluster\",obzone=~\"$obzone\",svr_ip=~\"$observer\",tenant_name=~\"$tenant_name\"}[$__rate_interval])) by ($group) + sum(rate(ob_sysstat{stat_id=\"40004\",ob_cluster_name=~\"$obcluster\",obzone=~\"$obzone\",svr_ip=~\"$observer\",tenant_name=~\"$tenant_name\"}[$__rate_interval])) by ($group) + sum(rate(ob_sysstat{stat_id=\"40006\",ob_cluster_name=~\"$obcluster\",obzone=~\"$obzone\",svr_ip=~\"$observer\",tenant_name=~\"$tenant_name\"}[$__rate_interval])) by ($group) + sum(rate(ob_sysstat{stat_id=\"40008\",ob_cluster_name=~\"$obcluster\",obzone=~\"$obzone\",svr_ip=~\"$observer\",tenant_name=~\"$tenant_name\"}[$__rate_interval])) by ($group) + sum(rate(ob_sysstat{stat_id=\"40000\",ob_cluster_name=~\"$obcluster\",obzone=~\"$obzone\",svr_ip=~\"$observer\",tenant_name=~\"$tenant_name\"}[$__rate_interval])) by ($group)",
     "legendFormat": "qps {{$group}}"
    }
   ]
  },
  {
   "title": "Cpu Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(ob_sysstat{stat_id=\"140006\",ob_cluster_name=~\"$obcluster\",obzone=~\"$obzone\",svr_ip=~\"$observer\",tenant_name=~\"$tenant_name\"}) by ($group) / sum(ob_sysstat{stat_id=\"140005\",ob_cluster_name=~\"$obcluster\",obzone=~\"$obzone\",svr_ip=~\"$observer\",tenant_name=~\"$tenant_name\"}) by ($group)",
     "legendFormat": "cpu util {{$group}}"
    }
   ]
  },
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"192.168.0.11:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "up{instance=\"192.168.0.12:9100\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "up{instance=\"192.168.0.13:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}